import type { Metadata } from "next";
import { AsciiBackground } from "@/components/ui/AsciiBackground";

export const revalidate = 0;

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions governing use of FlowForges services, subscriptions, and AI products.",
};

export default function TermsPage() {
  return (
    <div className="pt-24 pb-16 px-6">
      <div className="relative overflow-hidden rounded-2xl border border-[rgba(255,255,255,0.04)] bg-[rgba(255,255,255,0.01)] p-8 md:p-12 mb-10">
        <AsciiBackground mode="legal" className="absolute inset-0 w-full h-full opacity-40" />
        <div className="relative z-10">
          <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
          <p className="text-sm text-[#71717a] mt-2">Last updated: 2026-06-03 &nbsp;·&nbsp; Effective: 2026-06-03</p>
        </div>
      </div>

      <div className="mx-auto max-w-3xl">
        <div className="mt-10 space-y-10 text-[#a1a1aa] leading-relaxed">

          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) form a legally binding agreement between you
            (&ldquo;Customer&rdquo;, &ldquo;you&rdquo;) and <strong className="text-white">FlowForges</strong>,
            a brand operated by <strong className="text-white">AKS Forge Lab</strong>, a sole proprietorship
            registered in India (&ldquo;FlowForges&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;).
            By accessing our website at <em>flow-forges.com</em>, purchasing a subscription, or using any
            FlowForges product or service (collectively, the &ldquo;Services&rdquo;), you accept these Terms
            in full. If you are acting on behalf of an organisation, you represent that you have authority to
            bind that organisation.
          </p>
          <p>
            If you do not agree to these Terms, you must not access or use the Services.
          </p>

          {/* 1 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Definitions</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong className="text-white">Services</strong> — all FlowForges products, software, AI agents, APIs, dashboards, and support channels, including Prospecting OS and Remi.</li>
              <li><strong className="text-white">Subscription</strong> — a recurring paid plan granting access to a specific product tier.</li>
              <li><strong className="text-white">Setup Fee</strong> — a one-time charge for initial configuration, integration, and deployment of a product.</li>
              <li><strong className="text-white">User Content</strong> — any data, text, files, or instructions you submit to or generate through the Services.</li>
              <li><strong className="text-white">AI Output</strong> — any content, scores, messages, or recommendations generated by AI models within the Services.</li>
              <li><strong className="text-white">Dodo Payments</strong> — Dodo Payments Inc., our Merchant of Record, which processes all payments on our behalf.</li>
            </ul>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Eligibility &amp; Accounts</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must be at least 18 years old and legally capable of entering a binding contract in your jurisdiction.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.</li>
              <li>You must provide accurate, current, and complete information when creating an account and keep it updated.</li>
              <li>Notify us immediately at <a href="mailto:support@flow-forges.com" className="text-[#00d4ff] hover:underline">support@flow-forges.com</a> of any unauthorised access or suspected security breach.</li>
              <li>You may not share login credentials with third parties or allow concurrent access by multiple individuals on a single-seat plan.</li>
            </ul>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the Services for any unlawful, harmful, fraudulent, deceptive, or abusive purpose.</li>
              <li>Send unsolicited commercial messages (spam) in violation of applicable anti-spam laws, including the CAN-SPAM Act, CASL, and India&apos;s IT Act.</li>
              <li>Use AI Output to generate misleading, defamatory, harassing, or discriminatory content.</li>
              <li>Attempt to probe, scan, or test the vulnerability of any FlowForges system without written authorisation.</li>
              <li>Reverse-engineer, decompile, or disassemble any part of the Services.</li>
              <li>Use the Services to develop a competing product or service.</li>
              <li>Exceed reasonable rate limits or access the Services in a manner that impairs performance for other users.</li>
              <li>Upload content that infringes third-party intellectual property rights or applicable data protection law.</li>
            </ul>
            <p className="mt-3">
              Violation of this section may result in immediate suspension or termination of your account without
              refund, and we reserve the right to report illegal conduct to appropriate authorities.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Subscriptions, Setup Fees &amp; Billing</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Setup Fees</strong> are charged once at purchase. They cover initial
                configuration, phone number provisioning, integration setup, and deployment work.
                Setup fees are non-refundable once onboarding commences (see Refund Policy for exceptions).
              </li>
              <li>
                <strong className="text-white">Subscriptions</strong> begin on the date your setup is complete or
                on the date you activate the plan, whichever is earlier. Subscriptions auto-renew monthly
                unless cancelled before the renewal date.
              </li>
              <li>
                All payments are processed by <strong className="text-white">Dodo Payments</strong> as our Merchant of
                Record. All customers are billed in USD.
                Your bank statement will show &ldquo;<strong className="text-white">DODO* FLOWFORGES</strong>&rdquo;.
              </li>
              <li>
                Prices are subject to applicable taxes (including GST at the current rate). Tax amounts are
                disclosed at checkout.
              </li>
              <li>
                We reserve the right to change subscription pricing with at least <strong className="text-white">30 days&apos; notice</strong> via
                email. Your continued use after the notice period constitutes acceptance of the new price.
              </li>
              <li>
                If a payment fails, we will retry up to three times over seven days. Failure to resolve the
                payment may result in service suspension.
              </li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. AI Products — Specific Terms</h2>

            <h3 className="text-base font-semibold text-white mb-2 mt-4">5A. Prospecting OS</h3>
            <ul className="list-disc pl-5 space-y-2">
              <li>Prospecting OS scrapes publicly available data sources and scores leads against your Ideal Customer Profile (ICP). You are responsible for ensuring your use of scraped data complies with the terms of service of the data source and applicable privacy law.</li>
              <li>Lead data delivered through Prospecting OS is for your internal sales use only and may not be resold or redistributed.</li>
              <li>AI-generated icebreakers are suggestions only. You are responsible for reviewing and personalising outreach before sending.</li>
            </ul>

            <h3 className="text-base font-semibold text-white mb-2 mt-4">5B. Remi — Missed Call Recovery Agent</h3>
            <ul className="list-disc pl-5 space-y-2">
              <li>Remi sends automated SMS messages to individuals who call your business phone number. By activating Remi, you confirm you have a legitimate business relationship with or lawful basis to contact those callers.</li>
              <li>You are responsible for ensuring Remi&apos;s automated messaging complies with TCPA (US), PECR (UK), and other applicable telecommunications laws in the jurisdictions where you operate.</li>
              <li>You must include required opt-out language and honour opt-out requests. FlowForges will configure Remi with default compliant opt-out handling, but you bear final compliance responsibility.</li>
              <li>The US phone number provisioned for Remi remains FlowForges&apos; property and will be deprovisioned upon subscription termination.</li>
            </ul>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. AI Output Disclaimer</h2>
            <p>
              AI Outputs are generated probabilistically and may be inaccurate, incomplete, or inappropriate
              for your specific context. FlowForges makes no warranty that AI Outputs are factually correct,
              legally compliant, or suitable for any particular purpose. You are solely responsible for
              reviewing, validating, and taking responsibility for any action taken based on AI Output.
              AI Output does not constitute legal, financial, medical, or professional advice.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Our IP:</strong> FlowForges and its licensors retain all rights,
                title, and interest in the Services, including all software, models, algorithms, designs,
                branding, and documentation. Nothing in these Terms grants you any ownership right in the Services.
              </li>
              <li>
                <strong className="text-white">Licence to you:</strong> We grant you a limited, non-exclusive,
                non-transferable, revocable licence to access and use the Services solely for your internal
                business purposes during your subscription term.
              </li>
              <li>
                <strong className="text-white">Your Content:</strong> You retain ownership of all User Content
                you submit. You grant us a limited licence to process your User Content solely to provide
                the Services to you. We do not use your User Content to train AI models for use by other customers.
              </li>
              <li>
                <strong className="text-white">Feedback:</strong> Any feedback, suggestions, or ideas you
                provide are voluntary and non-confidential. We may use them freely without obligation or compensation.
              </li>
            </ul>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Confidentiality</h2>
            <p>
              Each party agrees to keep confidential any non-public information of the other party that is
              designated as confidential or that reasonably should be understood to be confidential given the
              nature of the information and circumstances of disclosure. This obligation does not apply to
              information that is publicly known, independently developed, or disclosed by law.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Third-Party Services</h2>
            <p>
              The Services integrate with third-party platforms including Twilio (SMS), Cal.com (scheduling),
              Slack (notifications), Apify (data sourcing), Supabase (database), and Vercel (hosting).
              Your use of these platforms is subject to their respective terms. We are not liable for
              interruptions or changes to third-party services, though we will endeavour to find alternatives
              if a material integration becomes unavailable.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Service Levels &amp; Availability</h2>
            <p>
              We target 99.5% uptime for productized Services. Scheduled maintenance is announced at least
              24 hours in advance via email. We are not liable for downtime caused by third-party infrastructure,
              force majeure events, or actions outside our reasonable control. Service credits for significant
              downtime may be negotiated in enterprise agreements.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Disclaimers</h2>
            <p>
              The Services are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without
              warranties of any kind, express or implied, including warranties of merchantability, fitness for
              a particular purpose, non-infringement, or uninterrupted operation. We do not warrant that the
              Services will meet your specific business requirements or that lead-generation results will meet
              any particular revenue or pipeline targets.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, FlowForges (operated by AKS Forge Lab) shall
              not be liable for any indirect, incidental, special, consequential, or punitive damages, including
              loss of profits, revenue, data, business opportunities, or goodwill, arising out of or in
              connection with these Terms or the Services, even if advised of the possibility of such damages.
            </p>
            <p className="mt-3">
              Our total aggregate liability for all claims arising under these Terms shall not exceed the
              greater of (a) the amounts paid by you to FlowForges in the three (3) months immediately
              preceding the event giving rise to the claim, or (b) USD $500.
            </p>
            <p className="mt-3">
              Some jurisdictions do not allow the exclusion or limitation of certain damages. In such
              jurisdictions, the above limitations apply to the maximum extent permitted by law.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">13. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless FlowForges, AKS Forge Lab, and their
              officers, employees, and agents from and against any claims, damages, losses, liabilities,
              costs, and expenses (including reasonable legal fees) arising from: (a) your use of the
              Services in violation of these Terms; (b) your User Content; (c) your violation of any
              applicable law; or (d) your violation of any third party&apos;s rights.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">14. Force Majeure</h2>
            <p>
              Neither party shall be liable for delays or failure to perform obligations due to causes beyond
              their reasonable control, including natural disasters, war, terrorism, pandemics, government
              actions, power failures, internet outages, or third-party service disruptions. The affected
              party shall give prompt notice and use reasonable efforts to resume performance.
            </p>
          </section>

          {/* 15 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">15. Termination</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You may cancel your subscription at any time via your account dashboard or by emailing support. Cancellation takes effect at the end of the current billing period.</li>
              <li>We may suspend or terminate your account with immediate effect for material breach of these Terms, non-payment, illegal activity, or if we reasonably believe continued access poses a security or legal risk.</li>
              <li>Upon termination, your licence to use the Services ceases immediately. Sections on IP, liability, indemnification, and governing law survive termination.</li>
              <li>We will retain and then delete your data per our Privacy Policy and applicable law.</li>
            </ul>
          </section>

          {/* 16 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">16. Consumer Rights (EU / UK)</h2>
            <p>
              If you are a consumer located in the European Union or United Kingdom, you may have a statutory
              right to withdraw from a digital service contract within 14 days of purchase (&ldquo;cooling-off
              period&rdquo;). However, by requesting that we commence setup or provision access before the
              14-day period expires, you acknowledge that the right of withdrawal is lost upon commencement of
              the service. We will confirm this in your order confirmation email.
            </p>
          </section>

          {/* 17 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">17. Dispute Resolution</h2>
            <p>
              We encourage you to contact us first at <a href="mailto:support@flow-forges.com" className="text-[#00d4ff] hover:underline">support@flow-forges.com</a> to
              resolve any dispute informally. If a dispute cannot be resolved within 30 days of written
              notice, either party may escalate to formal proceedings under the governing law below.
              Nothing in this section prevents either party from seeking urgent injunctive relief.
            </p>
          </section>

          {/* 18 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">18. Governing Law &amp; Jurisdiction</h2>
            <p>
              These Terms are governed by the laws of India. Subject to Section 16, any dispute that cannot
              be resolved informally shall be subject to the exclusive jurisdiction of the courts in
              Bhilai, Chhattisgarh 490023, India. If mandatory consumer protection laws in your jurisdiction
              provide additional rights that cannot be waived by contract, those rights are not affected.
            </p>
          </section>

          {/* 19 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">19. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. Material changes will be communicated via email
              and/or a notice within the Services at least 14 days before they take effect. Your continued
              use of the Services after the effective date constitutes acceptance of the revised Terms.
              If you do not agree to the changes, you must cancel your subscription before the effective date.
            </p>
          </section>

          {/* 20 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">20. General</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong className="text-white">Entire Agreement:</strong> These Terms, together with our Privacy Policy, Refund Policy, and any order confirmation, constitute the entire agreement between you and FlowForges regarding the Services.</li>
              <li><strong className="text-white">Severability:</strong> If any provision is found unenforceable, it shall be modified to the minimum extent necessary, and the remaining provisions remain in full force.</li>
              <li><strong className="text-white">No Waiver:</strong> Failure to enforce any right does not constitute a waiver of that right.</li>
              <li><strong className="text-white">Assignment:</strong> You may not assign your rights under these Terms without our written consent. We may assign our rights to an affiliate or successor entity.</li>
            </ul>
          </section>

          {/* 21 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">21. Contact</h2>
            <p>
              <strong className="text-white">FlowForges</strong> (operated by AKS Forge Lab)<br />
              Bhilai, Chhattisgarh 490023, India<br />
              GSTIN: 22MGSPS6643B1ZY<br /><br />
              Email:{" "}
              <a href="mailto:support@flow-forges.com" className="text-[#00d4ff] hover:underline">
                support@flow-forges.com
              </a><br />
              Phone:{" "}
              <a href="tel:+919630755104" className="text-[#00d4ff] hover:underline">
                +91 9630755104
              </a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
